version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi-application
    environment:
      - MONGO_URI
    ports:
      - '8000:8000'
    networks:
      - spelling-dee
    restart: always

networks:
  spelling-dee:
    driver: bridge
